plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'groovy'
    id "com.gradle.plugin-publish" version "1.2.1"
}


dependencies {
    implementation("org.eclipse.jgit:org.eclipse.jgit:7.4.0.202509020913-r")
    testImplementation('junit:junit:4.12')
    testImplementation('com.github.stefanbirkner:system-rules:1.19.0')
    testImplementation('com.github.stefanbirkner:system-lambda:1.1.1')
    implementation('org.ajoberstar.grgit:grgit-core:5.3.3')
}

repositories {
    maven {
        url = 'https://frcmaven.wpi.edu/artifactory/ex-mvn'
    }
}

version = '2027.0.2'
group = 'org.wpilib'

gradlePlugin {
    website = 'https://github.com/wpilibsuite/wpilib-version-plugin'
    vcsUrl = 'https://github.com/wpilibsuite/wpilib-version-plugin'
    plugins {
        wpilibVersionPlugin {
            id = 'org.wpilib.WPILibVersioningPlugin'
            displayName = 'WPILib Version Plugin'
            implementationClass = 'org.wpilib.versioning.WPILibVersioningPlugin'
            description = 'This plugin provides maven remote settings and versioning for the WPILib Suite FRC projects.'
            tags = ['groovy', 'version', 'maven', 'frc', 'wpilib']
        }
    }
}

tasks.withType(Test).configureEach {
    jvmArgs(["--add-opens=java.base/java.lang=ALL-UNNAMED",
             "--add-opens=java.base/java.util=ALL-UNNAMED"])
}

tasks.withType(Javadoc) {
    options.addBooleanOption('Xdoclint:all,-missing', true)
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:unchecked'
    options.deprecation = true
}

wrapper {
    gradleVersion = '9.2.0'
}
